Repository SmartX-Labs/SmartX-Mini, pull requests merged in 2025-03, with the labels that each got.

#130 Lab2 - 3월 15일 점검 결과 반영
  SmartX-Mini-2025 Collection/Experiment/Lab-2. InterConnect/Lab#2_InterConnect_v2R10_Eng.md
  SmartX-Mini-2025 Collection/Experiment/Lab-2. InterConnect/Lab#2_InterConnect_v2R10_Kor.md
Labels: enhancement

#133 Lab 3, 4, 5, 6 - Docs update
  SmartX-Box/Dockerfile
  SmartX-Box/IoT-labs/Dockerfile
  SmartX-Box/IoT-labs/RPI_capture.py
  SmartX-Box/IoT-labs/RPI_transfer.py
  SmartX-Box/IoT-labs/data.txt
  SmartX-Box/IoT-labs/process.sh
  SmartX-Box/IoT-labs/webserver.js
  SmartX-Box/README.md
  SmartX-Box/raspbian-flume/Dockerfile
  SmartX-Box/raspbian-flume/flume-conf.properties
  SmartX-Box/raspbian-flume/plugins.d/snmp-source/lib/flume-ng-snmp-source-0.0.1.jar
  SmartX-Box/raspbian-flume/plugins.d/snmp-source/libext/flume-ng-core-1.4.0.jar
  SmartX-Box/raspbian-flume/plugins.d/snmp-source/libext/json-20160810.jar
  SmartX-Box/raspbian-flume/plugins.d/snmp-source/libext/snmp4j-1.10.1.jar
  SmartX-Box/ubuntu-flume/Dockerfile
  SmartX-Box/ubuntu-flume/flume-conf.properties
  SmartX-Box/ubuntu-flume/plugins.d/snmp-source/lib/flume-ng-snmp-source-0.0.1.jar
  SmartX-Box/ubuntu-flume/plugins.d/snmp-source/libext/flume-ng-core-1.4.0.jar
  SmartX-Box/ubuntu-flume/plugins.d/snmp-source/libext/json-20160810.jar
  SmartX-Box/ubuntu-flume/plugins.d/snmp-source/libext/snmp4j-1.10.1.jar
  SmartX-Box/ubuntu-grafana/Resource Monitoring-1493646591511.json
  SmartX-Box/ubuntu-influx/.gitignore
  SmartX-Box/ubuntu-influx/influxdb.conf
  SmartX-Box/ubuntu-kafka/Dockerfile
  SmartX-Box/ubuntu-kafkatodb/.dockerignore
  SmartX-Box/ubuntu-kafkatodb/Dockerfile
  SmartX-Box/ubuntu-kafkatodb/broker_to_influxdb.py
  SmartX-Box/ubuntu-kafkatodb/kafka_to_db.js
  SmartX-Box/ubuntu-kafkatodb/package.json
  SmartX-Mini-2025 Collection/Experiment/Lab-3. IoT/Lab#3_IoT_kr.md
  SmartX-Mini-2025 Collection/Experiment/Lab-4. Tower/Lab#4_Tower.md
  SmartX-Mini-2025 Collection/Experiment/Lab-4. Tower/Lab#4_Tower_kr.md
  SmartX-Mini-2025 Collection/Experiment/Lab-5. Cluster/Lab#5._Cluster_kr.md
  SmartX-Mini-2025 Collection/Experiment/Lab-6. Analytics/Lab#6_Analytics_kr.md
Labels: enhancement

#139 Lab#2 - SmartX-Box 추가 및 2025 Dir 이름 변경에 따른 매뉴얼 수정
  SmartX-Box/raspbian-flume/Dockerfile
  SmartX-Box/ubuntu-kafka/Dockerfile
  SmartX-Mini-2025/Experiment/Lab-2. InterConnect/Lab#2_InterConnect_v2R10_Eng.md
  SmartX-Mini-2025/Experiment/Lab-2. InterConnect/Lab#2_InterConnect_v2R10_Kor.md
Labels: feat/update-content

#147 Lab1 - Docker 설치과정 수정, NUC 설명 추가 및 Lab5 - 오타 수정
  SmartX-Mini-2025/Experiment/Lab-1. Box/Lab#1_Box_Eng.md
  SmartX-Mini-2025/Experiment/Lab-1. Box/Lab#1_Box_Kor.md
  SmartX-Mini-2025/Experiment/Lab-5. Cluster/Lab#5._Cluster_kr.md
Labels: feat/new-content, feat/update-content
